[workspace]
resolver = "2"
members = [
    "lang",
]

[package]
name = "lithium"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
lang = { path = "lang" }
