[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.50"
lexer = { path = "../lexer" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
