name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building...
        run: cargo build --release --workspace
      - name: Testing...
        run: cargo test --release --workspace
      - name: Benchmarking...
        run: cargo bench --release --workspace
      - name: Saving results...
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: target/criterion
