name: Test
on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: Testing...
      run: cargo test --workspace
